### ISSUE TITLE
lsp not started 

### ISSUE THREAD

**Issue by mohamad-supangat** [fannheyward/coc-xml#518]
```
2024-01-02T14:05:19.059 INFO (pid:9997) [language-client-index] - Language server "xml" started with 10124
2024-01-02T14:05:19.153 INFO (pid:9997) [services] - LanguageClient XML LSP state change: stopped => starting
2024-01-02T14:05:19.153 ERROR (pid:9997) [language-client-client] - Server xml initialization failed. Dg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:52:4644)
    at Object.dispose (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:237:6192)
    at Md.handleConnectionClosed (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:240:15472)
    at Md.handleConnectionClosed (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:244:3541)
    at t (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:240:15121)
    at xP.invoke (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:24:14497)
    at oh.fire (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:24:15266)
    at et (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:26:7064)
    at xP.invoke (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:24:14497)
    at oh.fire (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:24:15266) {
  code: -32097,
  data: undefined
}
2024-01-02T14:05:19.153 INFO (pid:9997) [services] - LanguageClient XML LSP state change: starting => stopped
2024-01-02T14:05:19.159 INFO (pid:9997) [language-client-index] - Language server "xml" started with 10144
2024-01-02T14:05:19.249 ERROR (pid:9997) [language-client-client] - Server xml initialization failed. Dg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:52:4644)
    at Object.dispose (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:237:6192)
    at Md.handleConnectionClosed (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:240:15472)
    at Md.handleConnectionClosed (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:244:3541)
    at t (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:240:15121)
    at xP.invoke (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:24:14497)
    at oh.fire (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:24:15266)
    at et (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:26:7064)
    at xP.invoke (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:24:14497)
    at oh.fire (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:24:15266) {
  code: -32097,
  data: undefined
}
2024-01-02T14:05:22.262 INFO (pid:9997) [attach] - receive notification: format []
2024-01-02T14:05:22.267 ERROR (pid:9997) [attach] - Error on notification format Error: Format provider not found for buffer: 2
    at Dy.documentFormat (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:257:27946)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Dy.formatCurrentBuffer (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:257:27706)
    at async Gy.cocAction (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:277:46159)
    at async EventEmitter.<anonymous> (/home/deve/.local/share/nvim/lazy/coc.nvim/build/index.js:277:47778)
2024-01-02T14:05:26.850 INFO (pid:9997) [attach] - receive notification: showInfo []

```

**Comment by fannheyward** [comment]
What's your LemMinX version? Make sure LemMinX runs successfully in your env.

**Comment by mohamad-supangat** [comment]
tanks for reply, i remove all neovim and coc.nvim cache and reinstall all plugin and now work
